name: Deploy services

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Build and Push Indexer Docker Image
        run: |
          cd services &&
          docker build -f Dockerfile.indexer --platform linux/amd64 -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/soldex/soldex-indexer:latest . && 
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/soldex/soldex-indexer:latest

      - name: Deploy Indexer Service to Cloud Run
        run: |
          gcloud run deploy soldex-indexer \
          --image us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/soldex/soldex-indexer:latest \
          --region us-west1 \
          --platform managed \
          --allow-unauthenticated

      - name: Build and Push Server Docker Image
        run: |
          cd services &&
          docker build -f Dockerfile.server --platform linux/amd64 -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/soldex/soldex-server:latest . &&
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/soldex/soldex-server:latest

      - name: Deploy Server
        run: |
          cd services && 
          gcloud run deploy soldex-server \
          --image us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/soldex/soldex-server:latest \
          --region us-west1 \
          --platform managed \
          --allow-unauthenticated
